services:
  api:
    image: pmldl/api
    container_name: model_api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    networks:
      - network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app

  app:
    image: pmldl/web
    container_name: web_app
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - network
    environment:
      - API_URL=http://api:8000

networks:
  network:
    driver: bridge